# Generated by Django 5.2.4 on 2025-07-09 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updatad_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
