# Generated by Django 5.2.4 on 2025-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/')),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('thumbnail_medium', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('thumbnail_large', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
            ],
        ),
    ]
